### ISSUE TITLE
Retrieve link HTML title

### ISSUE THREAD

**Issue by ariejan** [ariejan/firefly#59]
When shortening an URL, Firefly should try to retrieve the remote HTML page and extract the title for display in the admin panel.

**Comment by volgorean** [comment]
I'll do this one if you don't mind.

**Comment by ariejan** [comment]
Go right ahead! Feel free to discuss options first here or on gitter.

**Comment by volgorean** [comment]
My first thought was just to use nokogiri in ItemRepository#create_from_url. However, that might slow down the create action noticeably.  We could also put the process in a worker along with any re-hosting tasks created at a later point. The problem with that, however, is that it might make it more difficult to deploy and less beginner friendly.

**Comment by volgorean** [comment]
Note that nokogiri is already a dependency in firefly.

**Comment by ariejan** [comment]
I think workers will be needed anyway, especially when we're going to re-host images. Sidekiq is my favourite as it's fast and not too much rails-oriented. We can figure out deployment later. Nokogiri seems like a good choice.

**Comment by volgorean** [comment]
Ok, I'll go for Sidekiq + Nokogiri then.
