### ISSUE TITLE
Allow text-hosting

### ISSUE THREAD

**Issue by ariejan** [ariejan/firefly#62]
Allow an item to consist of just text, optionally support syntax highlighting and rendering of markdown and other markup languages, if possible.

**Comment by volgorean** [comment]
I'll do this one too if you don't mind. Does the input have to be sanitized? Or are we working under the assumption that only an administrator will ever have access to this feature? Will firefly support user registration in the future?

**Comment by ariejan** [comment]
@volgorean feel free to claim anything you want :-) 

At first I would accept only plain text and show that as is (so that means escaped). Later we could add filters like markdown or an option to enable syntax highlighting. 

For now there's only one user, although it might be possible that, in the future, a Firefly instance will support multiple users. No open registration, though.
