### ISSUE TITLE
Generate QR code images for short URLs

### ISSUE THREAD

**Issue by ariejan** [ariejan/firefly#68]
As in Firefly 1.x, add an action for each item so you can download a QR code that contains the short URL.

**Comment by volgorean** [comment]
Sounds fun, I'll do this one.

**Comment by ariejan** [comment]
:+1:

**Comment by volgorean** [comment]
Should I also add an image icon to the link dash/list items? perhaps to the left of the trash icon? if so the project is using font awesome for icons all right?

**Comment by volgorean** [comment]
I submitted a pull request, I went ahead and added an icon link by the trash icon.  The qr code is a png.
