### ISSUE TITLE
Logo / Mascot

### ISSUE THREAD

**Issue by ariejan** [ariejan/firefly#69]
You know it!

Feel free to discuss here.

**Comment by volgorean** [comment]
![image](https://cloud.githubusercontent.com/assets/5345624/14237911/1272ab32-f9df-11e5-9168-0cb47c477d69.png)
I'm no designer but maby something along the lines of this haha. or perhaps a bug instead of the jar.

**Comment by ariejan** [comment]
@volgorean That bug in the jar actually sounds like a good idea. Or maybe just the bug? I guess we need to make some designer friends :-)

**Comment by RoelN** [comment]
Firefly — The software with the bug™ ;)

**Comment by yra99ary** [comment]
![firefly](https://cloud.githubusercontent.com/assets/8791195/14308470/f4138ffe-fc08-11e5-8cd2-14305d679973.png)
@ariejan How about this one ?
